### ISSUE TITLE
请删除 pushplus token 并改为从环境变量中获取

### ISSUE THREAD

**Issue by BlueHtml** [xiaoyulr/yyd#2]
pushplus token 是明文写在代码中的，请修改为从**环境变量**中获取，并及时**重置**你的token，以防被恶意调用。
<https://github.com/xiaoyulr/yyd/blob/49c0727939845de1fa50fb4ad9eca1199fff7e42/pddgy.py#L370>

**Comment by jiemo9527** [comment]
不好意思，插一嘴，push_token这个变量填写什么内容。感谢
